import type { AppLanguage } from "@/contexts/LanguageContext";

export const bibleBookNames: Record<string, Record<AppLanguage, string>> = {
  gen: { pt: "Gênesis", en: "Genesis", es: "Génesis" },
  exo: { pt: "Êxodo", en: "Exodus", es: "Éxodo" },
  lev: { pt: "Levítico", en: "Leviticus", es: "Levítico" },
  num: { pt: "Números", en: "Numbers", es: "Números" },
  deu: { pt: "Deuteronômio", en: "Deuteronomy", es: "Deuteronomio" },
  jos: { pt: "Josué", en: "Joshua", es: "Josué" },
  jdg: { pt: "Juízes", en: "Judges", es: "Jueces" },
  rut: { pt: "Rute", en: "Ruth", es: "Rut" },
  "1sa": { pt: "1 Samuel", en: "1 Samuel", es: "1 Samuel" },
  "2sa": { pt: "2 Samuel", en: "2 Samuel", es: "2 Samuel" },
  "1ki": { pt: "1 Reis", en: "1 Kings", es: "1 Reyes" },
  "2ki": { pt: "2 Reis", en: "2 Kings", es: "2 Reyes" },
  "1ch": { pt: "1 Crônicas", en: "1 Chronicles", es: "1 Crónicas" },
  "2ch": { pt: "2 Crônicas", en: "2 Chronicles", es: "2 Crónicas" },
  ezr: { pt: "Esdras", en: "Ezra", es: "Esdras" },
  neh: { pt: "Neemias", en: "Nehemiah", es: "Nehemías" },
  est: { pt: "Ester", en: "Esther", es: "Ester" },
  job: { pt: "Jó", en: "Job", es: "Job" },
  psa: { pt: "Salmos", en: "Psalms", es: "Salmos" },
  pro: { pt: "Provérbios", en: "Proverbs", es: "Proverbios" },
  ecc: { pt: "Eclesiastes", en: "Ecclesiastes", es: "Eclesiastés" },
  sng: { pt: "Cantares", en: "Song of Songs", es: "Cantares" },
  isa: { pt: "Isaías", en: "Isaiah", es: "Isaías" },
  jer: { pt: "Jeremias", en: "Jeremiah", es: "Jeremías" },
  lam: { pt: "Lamentações", en: "Lamentations", es: "Lamentaciones" },
  ezk: { pt: "Ezequiel", en: "Ezekiel", es: "Ezequiel" },
  dan: { pt: "Daniel", en: "Daniel", es: "Daniel" },
  hos: { pt: "Oséias", en: "Hosea", es: "Oseas" },
  jol: { pt: "Joel", en: "Joel", es: "Joel" },
  amo: { pt: "Amós", en: "Amos", es: "Amós" },
  oba: { pt: "Obadias", en: "Obadiah", es: "Abdías" },
  jon: { pt: "Jonas", en: "Jonah", es: "Jonás" },
  mic: { pt: "Miquéias", en: "Micah", es: "Miqueas" },
  nam: { pt: "Naum", en: "Nahum", es: "Nahúm" },
  hab: { pt: "Habacuque", en: "Habakkuk", es: "Habacuc" },
  zep: { pt: "Sofonias", en: "Zephaniah", es: "Sofonías" },
  hag: { pt: "Ageu", en: "Haggai", es: "Hageo" },
  zec: { pt: "Zacarias", en: "Zechariah", es: "Zacarías" },
  mal: { pt: "Malaquias", en: "Malachi", es: "Malaquías" },
  mat: { pt: "Mateus", en: "Matthew", es: "Mateo" },
  mrk: { pt: "Marcos", en: "Mark", es: "Marcos" },
  luk: { pt: "Lucas", en: "Luke", es: "Lucas" },
  jhn: { pt: "João", en: "John", es: "Juan" },
  act: { pt: "Atos", en: "Acts", es: "Hechos" },
  rom: { pt: "Romanos", en: "Romans", es: "Romanos" },
  "1co": { pt: "1 Coríntios", en: "1 Corinthians", es: "1 Corintios" },
  "2co": { pt: "2 Coríntios", en: "2 Corinthians", es: "2 Corintios" },
  gal: { pt: "Gálatas", en: "Galatians", es: "Gálatas" },
  eph: { pt: "Efésios", en: "Ephesians", es: "Efesios" },
  php: { pt: "Filipenses", en: "Philippians", es: "Filipenses" },
  col: { pt: "Colossenses", en: "Colossians", es: "Colosenses" },
  "1th": { pt: "1 Tessalonicenses", en: "1 Thessalonians", es: "1 Tesalonicenses" },
  "2th": { pt: "2 Tessalonicenses", en: "2 Thessalonians", es: "2 Tesalonicenses" },
  "1ti": { pt: "1 Timóteo", en: "1 Timothy", es: "1 Timoteo" },
  "2ti": { pt: "2 Timóteo", en: "2 Timothy", es: "2 Timoteo" },
  tit: { pt: "Tito", en: "Titus", es: "Tito" },
  phm: { pt: "Filemom", en: "Philemon", es: "Filemón" },
  heb: { pt: "Hebreus", en: "Hebrews", es: "Hebreos" },
  jas: { pt: "Tiago", en: "James", es: "Santiago" },
  "1pe": { pt: "1 Pedro", en: "1 Peter", es: "1 Pedro" },
  "2pe": { pt: "2 Pedro", en: "2 Peter", es: "2 Pedro" },
  "1jn": { pt: "1 João", en: "1 John", es: "1 Juan" },
  "2jn": { pt: "2 João", en: "2 John", es: "2 Juan" },
  "3jn": { pt: "3 João", en: "3 John", es: "3 Juan" },
  jud: { pt: "Judas", en: "Jude", es: "Judas" },
  rev: { pt: "Apocalipse", en: "Revelation", es: "Apocalipsis" },
};

export function getBookName(bookId: string, language: AppLanguage): string {
  return bibleBookNames[bookId]?.[language] || bibleBookNames[bookId]?.pt || bookId;
}
