export interface Verse {
  verse: number;
  text: string;
}

export interface Chapter {
  chapter: number;
  verses: Verse[];
}

// Evangelho de João - ACF (Almeida Corrigida Fiel)
export const johnChapters: Chapter[] = [
  {
    chapter: 1,
    verses: [
      { verse: 1, text: "NO princípio era o Verbo, e o Verbo estava com Deus, e o Verbo era Deus." },
      { verse: 2, text: "Ele estava no princípio com Deus." },
      { verse: 3, text: "Todas as coisas foram feitas por ele, e sem ele nada do que foi feito se fez." },
      { verse: 4, text: "Nele estava a vida, e a vida era a luz dos homens." },
      { verse: 5, text: "E a luz resplandece nas trevas, e as trevas não a compreenderam." },
      { verse: 6, text: "Houve um homem enviado de Deus, cujo nome era João." },
      { verse: 7, text: "Este veio para testemunho, para que testificasse da luz, para que todos cressem por ele." },
      { verse: 8, text: "Não era ele a luz, mas para que testificasse da luz." },
      { verse: 9, text: "Ali estava a luz verdadeira, que ilumina a todo o homem que vem ao mundo." },
      { verse: 10, text: "Estava no mundo, e o mundo foi feito por ele, e o mundo não o conheceu." },
      { verse: 11, text: "Veio para o que era seu, e os seus não o receberam." },
      { verse: 12, text: "Mas, a todos quantos o receberam, deu-lhes o poder de serem feitos filhos de Deus, aos que crêem no seu nome;" },
      { verse: 13, text: "Os quais não nasceram do sangue, nem da vontade da carne, nem da vontade do homem, mas de Deus." },
      { verse: 14, text: "E o Verbo se fez carne, e habitou entre nós, e vimos a sua glória, como a glória do unigênito do Pai, cheio de graça e de verdade." },
      { verse: 15, text: "João testificou dele, e clamou, dizendo: Este era aquele de quem eu dizia: O que vem após mim é antes de mim, porque foi primeiro do que eu." },
      { verse: 16, text: "E todos nós recebemos também da sua plenitude, e graça por graça." },
      { verse: 17, text: "Porque a lei foi dada por Moisés; a graça e a verdade vieram por Jesus Cristo." },
      { verse: 18, text: "Deus nunca foi visto por alguém. O Filho unigênito, que está no seio do Pai, esse o revelou." },
      { verse: 19, text: "E este é o testemunho de João, quando os judeus mandaram de Jerusalém sacerdotes e levitas para que lhe perguntassem: Quem és tu?" },
      { verse: 20, text: "E confessou, e não negou; mas confessou: Eu não sou o Cristo." },
      { verse: 21, text: "E perguntaram-lhe: Então quê? És tu Elias? E disse: Não sou. És tu profeta? E respondeu: Não." },
      { verse: 22, text: "Disseram-lhe pois: Quem és? para que demos resposta àqueles que nos enviaram; que dizes de ti mesmo?" },
      { verse: 23, text: "Disse: Eu sou a voz do que clama no deserto: Endireitai o caminho do Senhor, como disse o profeta Isaías." },
      { verse: 24, text: "E os que tinham sido enviados eram dos fariseus." },
      { verse: 25, text: "E perguntaram-lhe, e disseram-lhe: Por que batizas, pois, se tu não és o Cristo, nem Elias, nem o profeta?" },
      { verse: 26, text: "João respondeu-lhes, dizendo: Eu batizo com água; mas no meio de vós está um a quem vós não conheceis." },
      { verse: 27, text: "Este é aquele que vem após mim, que é antes de mim, do qual eu não sou digno de desatar a correia da alparca." },
      { verse: 28, text: "Estas coisas aconteceram em Betânia, do outro lado do Jordão, onde João estava batizando." },
      { verse: 29, text: "No dia seguinte João viu a Jesus, que vinha para ele, e disse: Eis o Cordeiro de Deus, que tira o pecado do mundo." },
      { verse: 30, text: "Este é aquele do qual eu disse: Após mim vem um homem que é antes de mim, porque foi primeiro do que eu." },
      { verse: 31, text: "E eu não o conhecia; mas, para que ele fosse manifestado a Israel, vim eu, por isso, batizando com água." },
      { verse: 32, text: "E João testificou, dizendo: Eu vi o Espírito descer do céu como pomba, e repousar sobre ele." },
      { verse: 33, text: "E eu não o conhecia, mas o que me mandou a batizar com água, esse me disse: Sobre aquele que vires descer o Espírito, e sobre ele repousar, esse é o que batiza com o Espírito Santo." },
      { verse: 34, text: "E eu vi, e tenho testificado que este é o Filho de Deus." },
      { verse: 35, text: "No dia seguinte João estava outra vez ali, e dois dos seus discípulos;" },
      { verse: 36, text: "E, vendo passar a Jesus, disse: Eis aqui o Cordeiro de Deus." },
      { verse: 37, text: "E os dois discípulos ouviram-no dizer isto, e seguiram a Jesus." },
      { verse: 38, text: "E Jesus, voltando-se e vendo que eles o seguiam, disse-lhes: Que buscais? E eles disseram: Rabi (que, traduzido, quer dizer Mestre), onde moras?" },
      { verse: 39, text: "Ele lhes disse: Vinde, e vede. Foram, e viram onde morava, e ficaram com ele aquele dia; e era já quase a hora décima." },
      { verse: 40, text: "Era André, irmão de Simão Pedro, um dos dois que ouviram isto de João, e o haviam seguido." },
      { verse: 41, text: "Este achou primeiro a seu irmão Simão, e disse-lhe: Achamos o Messias (que, traduzido, é o Cristo)." },
      { verse: 42, text: "E levou-o a Jesus. E, olhando Jesus para ele, disse: Tu és Simão, filho de Jonas; tu serás chamado Cefas (que quer dizer Pedro)." },
      { verse: 43, text: "No dia seguinte quis Jesus ir à Galiléia, e achou a Filipe, e disse-lhe: Segue-me." },
      { verse: 44, text: "E Filipe era de Betsaida, cidade de André e de Pedro." },
      { verse: 45, text: "Filipe achou Natanael, e disse-lhe: Havemos achado aquele de quem Moisés escreveu na lei, e os profetas: Jesus de Nazaré, filho de José." },
      { verse: 46, text: "Disse-lhe Natanael: Pode vir alguma coisa boa de Nazaré? Disse-lhe Filipe: Vem, e vê." },
      { verse: 47, text: "Jesus viu Natanael vir ter com ele, e disse dele: Eis aqui um verdadeiro israelita, em quem não há dolo." },
      { verse: 48, text: "Disse-lhe Natanael: De onde me conheces tu? Jesus respondeu, e disse-lhe: Antes que Filipe te chamasse, te vi eu, estando tu debaixo da figueira." },
      { verse: 49, text: "Natanael respondeu, e disse-lhe: Rabi, tu és o Filho de Deus; tu és o Rei de Israel." },
      { verse: 50, text: "Jesus respondeu, e disse-lhe: Porque te disse: Vi-te debaixo da figueira, crês? Coisas maiores do que estas verás." },
      { verse: 51, text: "E disse-lhe: Na verdade, na verdade vos digo que daqui em diante vereis o céu aberto, e os anjos de Deus subindo e descendo sobre o Filho do homem." },
    ]
  },
  {
    chapter: 2,
    verses: [
      { verse: 1, text: "E, AO terceiro dia, fizeram-se umas bodas em Caná da Galiléia; e estava ali a mãe de Jesus." },
      { verse: 2, text: "E foi também convidado Jesus e os seus discípulos para as bodas." },
      { verse: 3, text: "E, faltando vinho, a mãe de Jesus lhe disse: Não têm vinho." },
      { verse: 4, text: "Disse-lhe Jesus: Mulher, que tenho eu contigo? Ainda não é chegada a minha hora." },
      { verse: 5, text: "Sua mãe disse aos serventes: Fazei tudo quanto ele vos disser." },
      { verse: 6, text: "E estavam ali postas seis talhas de pedra, para as purificações dos judeus, e em cada uma cabiam dois ou três almudes." },
      { verse: 7, text: "Disse-lhes Jesus: Enchei de água essas talhas. E encheram-nas até em cima." },
      { verse: 8, text: "E disse-lhes: Tirai agora, e levai ao mestre-sala. E levaram." },
      { verse: 9, text: "E, logo que o mestre-sala provou a água feita vinho (não sabendo de onde viera, se bem que o sabiam os serventes que tinham tirado a água), chamou o mestre-sala ao esposo," },
      { verse: 10, text: "E disse-lhe: Todo o homem põe primeiro o vinho bom e, quando já têm bebido bem, então o inferior; mas tu guardaste até agora o bom vinho." },
      { verse: 11, text: "Jesus principiou assim os seus sinais em Caná da Galiléia, e manifestou a sua glória; e os seus discípulos creram nele." },
      { verse: 12, text: "Depois disto desceu a Cafarnaum, ele, e sua mãe, e seus irmãos, e seus discípulos; e ficaram ali não muitos dias." },
      { verse: 13, text: "E estava próxima a páscoa dos judeus, e Jesus subiu a Jerusalém." },
      { verse: 14, text: "E achou no templo os que vendiam bois, e ovelhas, e pombos, e os cambiadores assentados." },
      { verse: 15, text: "E tendo feito um azorrague de cordéis, lançou todos fora do templo, também os bois e ovelhas; e espalhou o dinheiro dos cambiadores, e derribou as mesas;" },
      { verse: 16, text: "E disse aos que vendiam pombos: Tirai daqui estes, e não façais da casa de meu Pai casa de venda." },
      { verse: 17, text: "E os seus discípulos lembraram-se do que está escrito: O zelo da tua casa me devorará." },
      { verse: 18, text: "Responderam, pois, os judeus, e disseram-lhe: Que sinal nos mostras para fazeres isto?" },
      { verse: 19, text: "Jesus respondeu, e disse-lhes: Derribai este templo, e em três dias o levantarei." },
      { verse: 20, text: "Disseram, pois, os judeus: Em quarenta e seis anos foi edificado este templo, e tu o levantarás em três dias?" },
      { verse: 21, text: "Mas ele falava do templo do seu corpo." },
      { verse: 22, text: "Quando, pois, ressuscitou dentre os mortos, os seus discípulos lembraram-se de que lhes dissera isto; e creram na Escritura, e na palavra que Jesus tinha dito." },
      { verse: 23, text: "E, estando ele em Jerusalém pela páscoa, durante a festa, muitos, vendo os sinais que fazia, creram no seu nome." },
      { verse: 24, text: "Mas o mesmo Jesus não confiava neles, porque a todos conhecia;" },
      { verse: 25, text: "E não necessitava de que alguém testificasse do homem, porque ele bem sabia o que havia no homem." },
    ]
  },
  {
    chapter: 3,
    verses: [
      { verse: 1, text: "E HAVIA entre os fariseus um homem, chamado Nicodemos, príncipe dos judeus." },
      { verse: 2, text: "Este foi ter de noite com Jesus, e disse-lhe: Rabi, bem sabemos que és Mestre, vindo de Deus; porque ninguém pode fazer estes sinais que tu fazes, se Deus não for com ele." },
      { verse: 3, text: "Jesus respondeu, e disse-lhe: Na verdade, na verdade te digo que aquele que não nascer de novo, não pode ver o reino de Deus." },
      { verse: 4, text: "Disse-lhe Nicodemos: Como pode um homem nascer, sendo velho? Pode, porventura, tornar a entrar no ventre de sua mãe, e nascer?" },
      { verse: 5, text: "Jesus respondeu: Na verdade, na verdade te digo que aquele que não nascer da água e do Espírito, não pode entrar no reino de Deus." },
      { verse: 6, text: "O que é nascido da carne é carne, e o que é nascido do Espírito é espírito." },
      { verse: 7, text: "Não te maravilhes de te ter dito: Necessário vos é nascer de novo." },
      { verse: 8, text: "O vento assopra onde quer, e ouves a sua voz, mas não sabes de onde vem, nem para onde vai; assim é todo aquele que é nascido do Espírito." },
      { verse: 9, text: "Nicodemos respondeu, e disse-lhe: Como pode ser isso?" },
      { verse: 10, text: "Jesus respondeu, e disse-lhe: Tu és mestre de Israel, e não sabes isto?" },
      { verse: 11, text: "Na verdade, na verdade te digo que nós dizemos o que sabemos, e testificamos o que vimos; e não aceitais o nosso testemunho." },
      { verse: 12, text: "Se vos falei de coisas terrestres, e não crestes, como crereis, se vos falar das celestiais?" },
      { verse: 13, text: "Ora, ninguém subiu ao céu, senão o que desceu do céu, o Filho do homem, que está no céu." },
      { verse: 14, text: "E, como Moisés levantou a serpente no deserto, assim importa que o Filho do homem seja levantado;" },
      { verse: 15, text: "Para que todo aquele que nele crê não pereça, mas tenha a vida eterna." },
      { verse: 16, text: "Porque Deus amou o mundo de tal maneira que deu o seu Filho unigênito, para que todo aquele que nele crê não pereça, mas tenha a vida eterna." },
      { verse: 17, text: "Porque Deus enviou o seu Filho ao mundo, não para que condenasse o mundo, mas para que o mundo fosse salvo por ele." },
      { verse: 18, text: "Quem crê nele não é condenado; mas quem não crê já está condenado, porquanto não crê no nome do unigênito Filho de Deus." },
      { verse: 19, text: "E a condenação é esta: Que a luz veio ao mundo, e os homens amaram mais as trevas do que a luz, porque as suas obras eram más." },
      { verse: 20, text: "Porque todo aquele que faz o mal odeia a luz, e não vem para a luz, para que as suas obras não sejam reprovadas." },
      { verse: 21, text: "Mas quem pratica a verdade vem para a luz, a fim de que as suas obras sejam manifestas, porque são feitas em Deus." },
      { verse: 22, text: "Depois disto foi Jesus com os seus discípulos para a terra da Judéia; e estava ali com eles, e batizava." },
      { verse: 23, text: "Ora, João batizava também em Enom, junto a Salim, porque havia ali muitas águas; e vinham ali, e eram batizados." },
      { verse: 24, text: "Porque ainda João não tinha sido lançado na prisão." },
      { verse: 25, text: "Houve então uma questão entre os discípulos de João e os judeus acerca da purificação." },
      { verse: 26, text: "E foram ter com João, e disseram-lhe: Rabi, aquele que estava contigo além do Jordão, do qual tu deste testemunho, ei-lo batizando, e todos vão ter com ele." },
      { verse: 27, text: "João respondeu, e disse: O homem não pode receber coisa alguma, se não lhe for dada do céu." },
      { verse: 28, text: "Vós mesmos me sois testemunhas de que disse: Eu não sou o Cristo, mas sou enviado adiante dele." },
      { verse: 29, text: "Aquele que tem a esposa é o esposo; mas o amigo do esposo, que lhe assiste e o ouve, alegra-se muito com a voz do esposo. Assim, pois, já este meu gozo está cumprido." },
      { verse: 30, text: "É necessário que ele cresça e que eu diminua." },
      { verse: 31, text: "Aquele que vem de cima é sobre todos; aquele que vem da terra é da terra e fala da terra. Aquele que vem do céu é sobre todos." },
      { verse: 32, text: "E aquilo que ele viu e ouviu isso testifica; e ninguém aceita o seu testemunho." },
      { verse: 33, text: "Aquele que aceitou o seu testemunho, esse confirmou que Deus é verdadeiro." },
      { verse: 34, text: "Porque aquele que Deus enviou fala as palavras de Deus; pois não lhe dá Deus o Espírito por medida." },
      { verse: 35, text: "O Pai ama o Filho, e todas as coisas entregou nas suas mãos." },
      { verse: 36, text: "Aquele que crê no Filho tem a vida eterna; mas aquele que não crê no Filho não verá a vida, mas a ira de Deus sobre ele permanece." },
    ]
  }
];
